title: Zhongshan Hu's Homepage
page-top-title: Zhongshan Hu
top-section-bg-text: 我剩下一个梦
home-subtitle: Zhongshan Hu&ensp;|&ensp;胡中山
copyright-text: '&copy; Zhongshan Hu 2023-2025. All Rights Reserved.'
